# Generated by Django 5.1.5 on 2025-01-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='inn',
            field=models.CharField(default='52462635721', max_length=15, verbose_name='ИНН организации'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_partner',
            field=models.BooleanField(default=False, verbose_name='Партнер?'),
        ),
    ]
