# Generated by Django 5.1.5 on 2025-01-23 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_inn_user_is_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='inn',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='ИНН организации'),
        ),
    ]
