# Generated by Django 5.1.5 on 2025-01-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_featuredproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='characteristics',
            field=models.TextField(blank=True, null=True, verbose_name='Характеристики'),
        ),
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='edssldfsldfs,dfop\nweropfkweopf\n2rpwef[pewfk', verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
