# Generated by Django 5.1.5 on 2025-01-23 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_characteristics_product_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='characteristics',
            new_name='attrs',
        ),
    ]
